### ISSUE TITLE
Force Refresh doesn't appear to work.

### ISSUE THREAD

**Issue by kingborehaha** [Meowmaritus/DSAnimStudio#1]
I was messing around with the player roll speed in c0000.anibnd in DS1 PTDE. Any changes I make work properly when closing the game and starting it again, but trying to force refresh/refresh on save doesn't seem to actually update anything.

**Comment by kingborehaha** [comment]
Sorry, didn't mention that this was in the 2.0 release build. I figured out how to compile the master branch and it looks like the program clarifies that those options are for DS3 only (aww).

So I guess this isn't actually an issue except for the description for the 2.0 release saying that the options work with DS1? (Assuming I wasn't just messing something up to begin with)

Sorry about not checking the current build immediately, I'm super inexperienced with github and a lot of this sort of stuff in general and it didn't occur to me to do so until recently. At least this whole process let me figure out how to compile source code!

**Comment by Meowmaritus** [comment]
:fatcat:
