### ISSUE TITLE
Some question and maybe wish list

### ISSUE THREAD

**Issue by ocarinas** [Meowmaritus/DSAnimStudio#14]
Anyway to remove texts on viewport? Like "R WPN MDL 0 Animation: NONE" that shows up when viewing a player character, those texts eat up half of my viewport space. And my maximum viewport box size is 536x402; Anyway to increase it? If there is none right now, is it possible to add one in future build?

Thanks in advance and good luck on the project!

**Comment by Meowmaritus** [comment]
You can't do either of those currently but you will be able to in 2.4.1 😺👍
